### ISSUE TITLE
Consult for release of your code

### ISSUE THREAD

**Issue by Yu-Fangxu** [liuyeah/K-HTC#1]
Hi, I read your paper and find it interesting, I wonder if and when will you release the code? Thanks!

**Comment by liuyeah** [comment]
Thank you very much for your interest in our work. 

Since I've been on an internship recently, I haven't had enough time to systematically organize the code at the moment. As soon as I finish my internship, I will organize the code and release it.

**Comment by peyote-e** [comment]
That would be great! Would love to understand how you implemented the KHLA. 
All the best for your internship.
