### ISSUE TITLE
code for data process

### ISSUE THREAD

**Issue by skyc26** [liuyeah/K-HTC#3]
Could you provide the processing code of the downloaded WOS and BGC datasets so that the corresponding results can be run？

**Comment by liuyeah** [comment]
Thank you for your interest in our work (K-HTC). Due the time reason, I cannot find the data preprocessing codes at the moment. Actually, it is not complicated except for the concept recognication process. As for the concept recognition, you can refer to https://github.com/INK-USC/KagNet, from which we developed our recognition codes.
