### ISSUE TITLE
Data preprocess problem

### ISSUE THREAD

**Issue by ttsey** [liuyeah/K-HTC#4]
Could you give a more detailed description of the input json? Or is it convenient to provide an example? I find myself confused running the code.

**Comment by ttsey** [comment]
Or could you explain the meaning of "concept_neighbor" in the json? I dont get it now.

**Comment by liuyeah** [comment]
As I introduced in the Repo, the "concept_neighbor" indicates the corresponding concept relation in the KG. And we have explained in our paper, "we set the neighbor num k = 3 for each concept."
